---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

cache:
  yarn: true

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

jobs:
  fail_fast: true

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      install:
        - yarn install --non-interactive
      script:
        - yarn lint:js
        - yarn lint:md
        - yarn test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
