---
language: node_js
node_js:
  - "8"

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - cat node_modules/ember-template-lint/package.json | grep \"version\"
  - cat node_modules/prettier/package.json | grep \"version\"
  - yarn lint:js
  - yarn test

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

jobs:
  fail_fast: true

  include:
    - stage: "Tests"
      name: "ember-template-lint 1.6.1"
      install: yarn install --frozen-lockfile --non-interactive

    - name: "ember-template-lint latest"
      install: yarn install --no-lockfile
