---
language: node_js
node_js:
  - "8"

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --frozen-lockfile --non-interactive

script:
  - yarn list --pattern "ember-template-lint|prettier" --depth=0
  - yarn lint:js
  - yarn lint:md
  - yarn test

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

jobs:
  fail_fast: true

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "ember-template-lint 1.6.1"

    - name: "ember-template-lint latest"
      install: yarn install --no-lockfile
